version: "3.8"
services:
  db:
    image: postgres
#    build:
#      context: ./db
#      dockerfile: Dockerfile-db
#    secrets:
#      - db-password
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    networks:
#      - spring-postgres
    environment:
      - POSTGRES_DB=my-db-postgresql
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
#  be:
#    build: src
#    container_name: demo-be
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      - POSTGRES_DB=dbPostgresTest
#    networks:
#      - spring-postgres
#
#volumes:
#  db-data:
#networks:
#  spring-postgres:
